version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "1234:1234"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: mu-api.env
